import {
  Injectable,
  NotFoundException,
  ConflictException,
  BadRequestException,
  ForbiddenException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, FindManyOptions, FindOptionsWhere, Not, IsNull, In } from 'typeorm';
import * as QRCode from 'qrcode';
// UUID will be auto-generated by TypeORM PrimaryGeneratedColumn

import { Equipment, EquipmentType, EquipmentStatus, ClassificationTag, Condition } from '../models/equipment.entity';
import { User, UserRole } from '../models/user.entity';
import { Transfer, TransferType } from '../models/transfer.entity';
import { AuditLog, AuditAction } from '../models/audit-log.entity';

export interface CreateEquipmentDto {
  serialNumber: string;
  brand: string;
  model: string;
  type: EquipmentType;
  purchaseDate: Date;
  classificationTag: ClassificationTag;
  condition?: Condition;
  notes?: string;
}

export interface UpdateEquipmentDto {
  brand?: string;
  model?: string;
  status?: EquipmentStatus;
  condition?: Condition;
  notes?: string;
}

export interface EquipmentFilters {
  status?: EquipmentStatus;
  type?: EquipmentType;
  currentOwnerId?: string;
  classificationTag?: ClassificationTag;
  condition?: Condition;
  brand?: string;
  search?: string; // Search across brand, model, serialNumber
}

export interface PaginationOptions {
  page?: number;
  limit?: number;
}

export interface PaginatedResult<T> {
  items: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

export interface EquipmentWithMobileOptimization extends Omit<Equipment, 'generateQRCode'> {
  mobileOptimized?: boolean;
  availableActions?: string[];
  canReportCondition?: boolean;
  scanLogged?: boolean;
  scanTimestamp?: Date;
  responseTime?: number;
}

export interface EquipmentStats {
  total: number;
  available: number;
  assigned: number;
  pending: number;
  broken: number;
  stolen: number;
  byType: Record<EquipmentType, number>;
  byCondition: Record<Condition, number>;
  byClassification: Record<ClassificationTag, number>;
}

export interface InitiateTransferDto {
  toUserId?: string | null;
  fromUserId?: string | null;
  reason: string;
}

@Injectable()
export class EquipmentService {
  constructor(
    @InjectRepository(Equipment)
    private readonly equipmentRepository: Repository<Equipment>,
    @InjectRepository(User)
    private readonly userRepository: Repository<User>,
    @InjectRepository(Transfer)
    private readonly transferRepository: Repository<Transfer>,
    @InjectRepository(AuditLog)
    private readonly auditLogRepository: Repository<AuditLog>,
  ) {}

  /**
   * Create equipment with auto-generated QR code
   */
  async create(equipmentData: CreateEquipmentDto, currentUser: User): Promise<Equipment> {
    // Only admins can create equipment
    if (currentUser.role !== UserRole.ADMIN) {
      throw new ForbiddenException('Only administrators can register new equipment');
    }

    // Validate serial number uniqueness
    const existingEquipment = await this.equipmentRepository.findOne({
      where: { serialNumber: equipmentData.serialNumber }
    });

    if (existingEquipment) {
      throw new ConflictException('Equipment with this serial number already exists');
    }

    // Create equipment entity (ID will be auto-generated by TypeORM)
    const equipment = this.equipmentRepository.create({
      ...equipmentData,
      condition: equipmentData.condition || Condition.NEW,
      status: EquipmentStatus.AVAILABLE,
      currentOwnerId: null,
    });

    const savedEquipment = await this.equipmentRepository.save(equipment);

    // Generate QR code after equipment is saved and has an ID
    const qrCode = await this.generateQRCode(savedEquipment.id);

    // Update equipment with QR code
    const updatedEquipment = await this.equipmentRepository.save({
      ...savedEquipment,
      qrCode,
    });

    // Log equipment creation
    await this.createAuditLog(
      'equipment',
      updatedEquipment.id,
      currentUser.id,
      AuditAction.CREATE,
      null,
      {
        serialNumber: updatedEquipment.serialNumber,
        type: updatedEquipment.type,
        brand: updatedEquipment.brand,
        model: updatedEquipment.model,
        qrCode: updatedEquipment.qrCode,
      }
    );

    // Return the equipment with all relations
    return this.findById(updatedEquipment.id);
  }

  /**
   * Get all equipment with role-based filtering
   */
  async findAll(
    filters: EquipmentFilters = {},
    pagination: PaginationOptions = {},
    currentUser: User
  ): Promise<PaginatedResult<Equipment>> {
    const { page = 1, limit = 20 } = pagination;
    const skip = (page - 1) * limit;

    const whereConditions: FindOptionsWhere<Equipment> = {};

    // Role-based filtering: employees see only their own equipment
    if (currentUser.role === UserRole.EMPLOYEE) {
      whereConditions.currentOwnerId = currentUser.id;
    }

    // Apply additional filters
    if (filters.status) {
      whereConditions.status = filters.status;
    }

    if (filters.type) {
      whereConditions.type = filters.type;
    }

    if (filters.currentOwnerId && currentUser.role !== UserRole.EMPLOYEE) {
      whereConditions.currentOwnerId = filters.currentOwnerId;
    }

    if (filters.classificationTag) {
      whereConditions.classificationTag = filters.classificationTag;
    }

    if (filters.condition) {
      whereConditions.condition = filters.condition;
    }

    if (filters.brand) {
      whereConditions.brand = filters.brand;
    }

    let queryBuilder = this.equipmentRepository
      .createQueryBuilder('equipment')
      .leftJoinAndSelect('equipment.currentOwner', 'currentOwner')
      .leftJoinAndSelect('equipment.transfers', 'transfers')
      .leftJoinAndSelect('transfers.fromUser', 'fromUser')
      .leftJoinAndSelect('transfers.toUser', 'toUser')
      .where(whereConditions)
      .orderBy('equipment.createdAt', 'DESC')
      .skip(skip)
      .take(limit);

    // Handle search across multiple fields
    if (filters.search) {
      queryBuilder = queryBuilder.andWhere(
        '(equipment.brand ILIKE :search OR equipment.model ILIKE :search OR equipment.serialNumber ILIKE :search)',
        { search: `%${filters.search}%` }
      );
    }

    const [equipment, total] = await queryBuilder.getManyAndCount();

    return {
      items: equipment,
      pagination: {
        page,
        limit,
        total,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  /**
   * Get equipment by ID with transfer history
   */
  async findById(id: string): Promise<Equipment> {
    const equipment = await this.equipmentRepository.findOne({
      where: { id },
      relations: [
        'currentOwner',
        'transfers',
        'transfers.fromUser',
        'transfers.toUser',
        'requests',
      ],
    });

    if (!equipment) {
      throw new NotFoundException('Equipment not found');
    }

    return equipment;
  }

  /**
   * Quick lookup by QR code for mobile scanning with performance optimization
   */
  async findByQR(qrCode: string, currentUser: User, scanMetadata?: any): Promise<EquipmentWithMobileOptimization> {
    const startTime = Date.now();

    // Optimized query with selective relations
    const equipment = await this.equipmentRepository.findOne({
      where: { qrCode },
      relations: [
        'currentOwner',
        'transfers',
        'transfers.fromUser',
        'transfers.toUser',
      ],
    });

    if (!equipment) {
      throw new NotFoundException('Equipment not found for QR code');
    }

    const responseTime = Date.now() - startTime;

    // Role-based visibility for QR scan
    let canReportCondition = false;
    let availableActions: string[] = [];

    if (currentUser.role === UserRole.ADMIN) {
      availableActions = ['view', 'edit', 'transfer', 'reportCondition'];
      canReportCondition = true;
    } else if (equipment.currentOwnerId === currentUser.id) {
      availableActions = ['view', 'reportCondition'];
      canReportCondition = true;
    } else {
      availableActions = ['view'];
    }

    // Log QR scan event for audit
    const scanTimestamp = new Date();
    await this.createAuditLog(
      'equipment_scan',
      equipment.id,
      currentUser.id,
      AuditAction.CREATE,
      null,
      {
        scanSource: scanMetadata?.scanSource || 'unknown',
        userAgent: scanMetadata?.userAgent,
        ip: scanMetadata?.ip,
        responseTime,
      }
    );

    const result: EquipmentWithMobileOptimization = {
      ...equipment,
      mobileOptimized: true,
      availableActions,
      canReportCondition,
      scanLogged: true,
      scanTimestamp,
      responseTime,
    };

    return result;
  }

  /**
   * Update equipment details with authorization checks
   */
  async update(id: string, updateData: UpdateEquipmentDto, currentUser: User): Promise<Equipment> {
    const equipment = await this.findById(id);
    const oldValues = { ...equipment };

    // Authorization checks
    if (currentUser.role === UserRole.EMPLOYEE) {
      // Employees can only update condition and notes of their own equipment
      if (equipment.currentOwnerId !== currentUser.id) {
        throw new ForbiddenException('You can only update equipment assigned to you');
      }

      // Restrict what employees can update
      const allowedFields = ['condition', 'notes'];
      const updateFields = Object.keys(updateData);
      const unauthorizedFields = updateFields.filter(field => !allowedFields.includes(field));

      if (unauthorizedFields.length > 0) {
        throw new ForbiddenException(`You can only update: ${allowedFields.join(', ')}`);
      }
    }

    // Validate status transitions
    if (updateData.status && updateData.status !== equipment.status) {
      this.validateStatusTransition(equipment.status, updateData.status, currentUser);
    }

    // Update equipment
    await this.equipmentRepository.update(id, updateData);

    // Log the update
    await this.createAuditLog(
      'equipment',
      id,
      currentUser.id,
      AuditAction.UPDATE,
      oldValues,
      updateData
    );

    return this.findById(id);
  }

  /**
   * Update equipment condition with audit trail
   */
  async updateCondition(id: string, condition: Condition, notes: string, currentUser: User): Promise<Equipment> {
    const equipment = await this.findById(id);

    // Authorization: only owner or admin can update condition
    if (currentUser.role === UserRole.EMPLOYEE && equipment.currentOwnerId !== currentUser.id) {
      throw new ForbiddenException('You can only update condition of equipment assigned to you');
    }

    const oldValues = {
      condition: equipment.condition,
      notes: equipment.notes,
    };

    const updateData = {
      condition,
      notes,
      updatedAt: new Date(),
    };

    await this.equipmentRepository.update(id, updateData);

    // Log condition update specifically
    await this.createAuditLog(
      'equipment_condition',
      id,
      currentUser.id,
      AuditAction.UPDATE,
      oldValues,
      { condition, notes }
    );

    return this.findById(id);
  }

  /**
   * Get complete transfer history for equipment
   */
  async getTransferHistory(id: string, currentUser: User): Promise<Transfer[]> {
    const equipment = await this.findById(id);

    // Role-based access to transfer history
    if (currentUser.role === UserRole.EMPLOYEE) {
      // Employees can only see transfer history for their own equipment
      if (equipment.currentOwnerId !== currentUser.id) {
        throw new ForbiddenException('You can only view transfer history for your own equipment');
      }
    }

    return this.transferRepository.find({
      where: { equipmentId: id },
      relations: ['fromUser', 'toUser'],
      order: { createdAt: 'DESC' },
    });
  }

  /**
   * Initiate equipment transfer
   */
  async initiateTransfer(
    equipmentId: string,
    transferData: InitiateTransferDto,
    currentUser: User
  ): Promise<Transfer> {
    // Only admins and team leads can initiate transfers
    if (currentUser.role === UserRole.EMPLOYEE) {
      throw new ForbiddenException('Only administrators and team leads can initiate equipment transfers');
    }

    const equipment = await this.findById(equipmentId);

    // Validate equipment can be transferred
    if (equipment.status === EquipmentStatus.PENDING) {
      throw new BadRequestException('Equipment is already pending transfer');
    }

    if (equipment.status === EquipmentStatus.BROKEN || equipment.status === EquipmentStatus.STOLEN) {
      throw new BadRequestException('Cannot transfer equipment in current status');
    }

    // Validate target user if provided
    if (transferData.toUserId) {
      const targetUser = await this.userRepository.findOne({
        where: { id: transferData.toUserId, isActive: true }
      });

      if (!targetUser) {
        throw new BadRequestException('Target user not found or inactive');
      }
    }

    // Determine transfer type
    const transferType = Transfer.determineTransferType(
      equipment.currentOwnerId,
      transferData.toUserId
    );

    // Create transfer record
    const transfer = this.transferRepository.create({
      equipmentId,
      fromUserId: equipment.currentOwnerId,
      toUserId: transferData.toUserId,
      transferType,
      reason: transferData.reason,
      fromUserConfirmed: false,
      toUserConfirmed: false,
      adminConfirmed: false,
    });

    const savedTransfer = await this.transferRepository.save(transfer);

    // Update equipment status to pending
    await this.equipmentRepository.update(equipmentId, {
      status: EquipmentStatus.PENDING,
    });

    // Log transfer initiation
    await this.createAuditLog(
      'equipment_transfer',
      equipmentId,
      currentUser.id,
      AuditAction.CREATE,
      null,
      {
        transferId: savedTransfer.id,
        transferType,
        fromUserId: equipment.currentOwnerId,
        toUserId: transferData.toUserId,
        reason: transferData.reason,
      }
    );

    return this.transferRepository.findOne({
      where: { id: savedTransfer.id },
      relations: ['fromUser', 'toUser', 'equipment'],
    });
  }

  /**
   * Delete equipment with validation
   */
  async delete(id: string, currentUser: User): Promise<void> {
    // Only admins can delete equipment
    if (currentUser.role !== UserRole.ADMIN) {
      throw new ForbiddenException('Only administrators can delete equipment');
    }

    const equipment = await this.findById(id);

    // Validate equipment can be deleted
    if (equipment.status === EquipmentStatus.ASSIGNED) {
      throw new BadRequestException('Cannot delete assigned equipment. Return to pool first.');
    }

    if (equipment.status === EquipmentStatus.PENDING) {
      throw new BadRequestException('Cannot delete equipment with pending transfers');
    }

    // Log deletion before removing
    await this.createAuditLog(
      'equipment',
      id,
      currentUser.id,
      AuditAction.DELETE,
      {
        serialNumber: equipment.serialNumber,
        type: equipment.type,
        brand: equipment.brand,
        model: equipment.model,
        status: equipment.status,
      },
      null
    );

    await this.equipmentRepository.delete(id);
  }

  /**
   * Regenerate QR code for equipment
   */
  async regenerateQRCode(id: string, currentUser: User): Promise<Equipment> {
    // Only admins can regenerate QR codes
    if (currentUser.role !== UserRole.ADMIN) {
      throw new ForbiddenException('Only administrators can regenerate QR codes');
    }

    const equipment = await this.findById(id);
    const oldQrCode = equipment.qrCode;

    // Generate new QR code
    const newQrCode = await this.generateQRCode(id);

    await this.equipmentRepository.update(id, {
      qrCode: newQrCode,
      updatedAt: new Date(),
    });

    // Log QR code regeneration
    await this.createAuditLog(
      'equipment_qr',
      id,
      currentUser.id,
      AuditAction.UPDATE,
      { qrCode: oldQrCode },
      { qrCode: newQrCode }
    );

    return this.findById(id);
  }

  /**
   * Get equipment statistics for dashboard
   */
  async getEquipmentStats(): Promise<EquipmentStats> {
    const [
      total,
      available,
      assigned,
      pending,
      broken,
      stolen,
      typeStats,
      conditionStats,
      classificationStats,
    ] = await Promise.all([
      this.equipmentRepository.count(),
      this.equipmentRepository.count({ where: { status: EquipmentStatus.AVAILABLE } }),
      this.equipmentRepository.count({ where: { status: EquipmentStatus.ASSIGNED } }),
      this.equipmentRepository.count({ where: { status: EquipmentStatus.PENDING } }),
      this.equipmentRepository.count({ where: { status: EquipmentStatus.BROKEN } }),
      this.equipmentRepository.count({ where: { status: EquipmentStatus.STOLEN } }),
      this.equipmentRepository
        .createQueryBuilder('equipment')
        .select('equipment.type', 'type')
        .addSelect('COUNT(*)', 'count')
        .groupBy('equipment.type')
        .getRawMany(),
      this.equipmentRepository
        .createQueryBuilder('equipment')
        .select('equipment.condition', 'condition')
        .addSelect('COUNT(*)', 'count')
        .groupBy('equipment.condition')
        .getRawMany(),
      this.equipmentRepository
        .createQueryBuilder('equipment')
        .select('equipment.classificationTag', 'classificationTag')
        .addSelect('COUNT(*)', 'count')
        .groupBy('equipment.classificationTag')
        .getRawMany(),
    ]);

    const byType = Object.values(EquipmentType).reduce((acc, type) => {
      acc[type] = 0;
      return acc;
    }, {} as Record<EquipmentType, number>);

    const byCondition = Object.values(Condition).reduce((acc, condition) => {
      acc[condition] = 0;
      return acc;
    }, {} as Record<Condition, number>);

    const byClassification = Object.values(ClassificationTag).reduce((acc, tag) => {
      acc[tag] = 0;
      return acc;
    }, {} as Record<ClassificationTag, number>);

    // Populate statistics
    typeStats.forEach(stat => {
      byType[stat.type as EquipmentType] = parseInt(stat.count);
    });

    conditionStats.forEach(stat => {
      byCondition[stat.condition as Condition] = parseInt(stat.count);
    });

    classificationStats.forEach(stat => {
      byClassification[stat.classificationTag as ClassificationTag] = parseInt(stat.count);
    });

    return {
      total,
      available,
      assigned,
      pending,
      broken,
      stolen,
      byType,
      byCondition,
      byClassification,
    };
  }

  /**
   * Find equipment by QR code (alias for findByQR)
   */
  async findByQRCode(qrCode: string, currentUser: User): Promise<EquipmentWithMobileOptimization> {
    return this.findByQR(qrCode, currentUser);
  }

  /**
   * Log successful QR scan
   */
  async logQRScan(equipmentId: string, userId: string, responseTime: number): Promise<void> {
    await this.createAuditLog(
      'equipment_qr_scan',
      equipmentId,
      userId,
      AuditAction.CREATE,
      {},
      { responseTime, scanTime: new Date().toISOString() }
    );
  }

  /**
   * Log failed QR scan
   */
  async logQRScanFailure(qrCode: string, userId: string, responseTime: number, errorMessage: string): Promise<void> {
    await this.createAuditLog(
      'equipment_qr_scan_failure',
      qrCode,
      userId,
      AuditAction.CREATE,
      {},
      { responseTime, errorMessage, scanTime: new Date().toISOString() }
    );
  }

  /**
   * Generate QR code image (alias for regenerateQRCode)
   */
  async generateQRCodeImage(id: string, currentUser: User): Promise<Equipment> {
    return this.regenerateQRCode(id, currentUser);
  }

  /**
   * Private method to generate QR code
   */
  private async generateQRCode(equipmentId: string): Promise<string> {
    try {
      return await QRCode.toDataURL(equipmentId, {
        width: 200,
        margin: 2,
        color: {
          dark: '#000000',
          light: '#FFFFFF',
        },
      });
    } catch (error) {
      throw new BadRequestException('Failed to generate QR code');
    }
  }

  /**
   * Private method to validate status transitions
   */
  private validateStatusTransition(
    currentStatus: EquipmentStatus,
    newStatus: EquipmentStatus,
    currentUser: User
  ): void {
    // Only admins can change status directly
    if (currentUser.role !== UserRole.ADMIN) {
      throw new ForbiddenException('Only administrators can change equipment status directly');
    }

    // Define valid transitions
    const validTransitions: Record<EquipmentStatus, EquipmentStatus[]> = {
      [EquipmentStatus.AVAILABLE]: [
        EquipmentStatus.ASSIGNED,
        EquipmentStatus.PENDING,
        EquipmentStatus.BROKEN,
        EquipmentStatus.STOLEN,
      ],
      [EquipmentStatus.ASSIGNED]: [
        EquipmentStatus.PENDING,
        EquipmentStatus.BROKEN,
        EquipmentStatus.STOLEN,
      ],
      [EquipmentStatus.PENDING]: [
        EquipmentStatus.AVAILABLE,
        EquipmentStatus.ASSIGNED,
        EquipmentStatus.BROKEN,
        EquipmentStatus.STOLEN,
      ],
      [EquipmentStatus.BROKEN]: [
        EquipmentStatus.AVAILABLE,
        EquipmentStatus.STOLEN,
      ],
      [EquipmentStatus.STOLEN]: [
        EquipmentStatus.AVAILABLE,
      ],
    };

    if (!validTransitions[currentStatus]?.includes(newStatus)) {
      throw new BadRequestException(
        `Invalid status transition from ${currentStatus} to ${newStatus}`
      );
    }
  }

  /**
   * Private method to create audit logs
   */
  private async createAuditLog(
    entityType: string,
    entityId: string,
    userId: string,
    action: AuditAction,
    oldValues: any,
    newValues: any,
    metadata?: any
  ): Promise<void> {
    const auditLog = this.auditLogRepository.create({
      entityType,
      entityId,
      action,
      userId,
      oldValues,
      newValues,
      metadata,
    });

    await this.auditLogRepository.save(auditLog);
  }
}